# Generated by Django 3.0.2 on 2020-02-01 15:54

from django.db import migrations, models
import travel.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20200201_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='from_time',
            field=models.DateTimeField(validators=[travel.models.present_or_future_date]),
        ),
    ]
