# Generated by Django 2.2.9 on 2020-02-02 10:42

from django.db import migrations, models
import travel.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20200201_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='from_time',
            field=models.DateField(validators=[travel.models.present_or_future_date]),
        ),
    ]
