# Generated by Django 2.2.9 on 2020-02-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20200202_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='from_time',
            field=models.TimeField(),
        ),
    ]
