# Generated by Django 2.2.9 on 2020-02-02 15:22

from django.db import migrations, models
import travel.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20200202_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='from_time',
            field=models.DateTimeField(validators=[travel.models.present_or_future_date]),
        ),
    ]
